---

- name: Ansible Playbook for Elastic on google-compute-instances
  hosts: elastic-instances
  remote_user: "{{ deployer }}"
  become: yes
  become_method: sudo
  vars_files:
    - vars/common.yml
  roles:
    - bootstrap
#    - conda
    - elastic

