name: {{ conda_environment_name }}
dependencies:
- elasticsearch=6.3.1
- gensim=3.4.0
- jupyter=1.0.0
- pip=19.1
- python=3.6.7
- seaborn=0.9.0
- scikit-learn=0.20.3
- pip:
  - google_compute_engine
  - ijson==2.3
  - pystemmer==1.3.0
  - pyxdameraulevenshtein==1.5.3
  - spacy==2.1.3