name: {{ conda_environment_name }}
dependencies:
- elasticsearch=6.2.0
- jupyter=1.0.0
- pip=9.0.3
- python=3.6.5
- seaborn=0.8.1
- scikit-learn=0.19.1
- pip:
  - ijson==2.3
  - pystemmer==1.3.0
  - pyxdameraulevenshtein==1.5
  - spacy==2.0.11
