# conda env create -f environment.yml
#   or to update:
# conda env update -f environment.yml
#   using the environment:
# source activate provision-training-environment
name: provision-training-environment
channels:
  - defaults      # anaconda
  - conda-forge
dependencies:
  - python=3.6
  - ansible=>2.5.4
  - bcrypt
  - click
  - jinja2
  - paramiko
  - delegator

